// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartMenza.Data.Data;

#nullable disable

namespace SmartMenza.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251203115630_IspravakFunkcije3")]
    partial class IspravakFunkcije3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartMenza.Data.Models.DailyFoodIntakeDto", b =>
                {
                    b.Property<int>("dailyFoodIntakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dailyFoodIntakeId"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("dishId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("dailyFoodIntakeId");

                    b.HasIndex("dishId");

                    b.HasIndex("userId");

                    b.ToTable("DailyFoodIntakes");

                    b.HasData(
                        new
                        {
                            dailyFoodIntakeId = 1,
                            date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dishId = 1,
                            userId = 2
                        },
                        new
                        {
                            dailyFoodIntakeId = 2,
                            date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dishId = 2,
                            userId = 2
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Models.DailyMenuDishDto", b =>
                {
                    b.Property<int>("dailyMenuId")
                        .HasColumnType("int");

                    b.Property<int>("dishId")
                        .HasColumnType("int");

                    b.HasKey("dailyMenuId", "dishId");

                    b.HasIndex("dishId");

                    b.ToTable("DailyMenuDishes");

                    b.HasData(
                        new
                        {
                            dailyMenuId = 1,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 1,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 1,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 2,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 2,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 3,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 3,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 4,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 4,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 4,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 5,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 5,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 6,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 6,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 7,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 7,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 8,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 8,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 8,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 9,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 9,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 9,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 10,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 10,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 11,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 11,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 11,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 12,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 12,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 13,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 13,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 14,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 14,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 14,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 15,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 15,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 16,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 16,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 17,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 17,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 18,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 18,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 18,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 19,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 19,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 19,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 20,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 20,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 21,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 21,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 21,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 22,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 22,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 23,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 23,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 24,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 24,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 24,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 25,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 25,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 26,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 26,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 27,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 27,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 28,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 28,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 28,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 29,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 29,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 29,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 30,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 30,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 31,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 31,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 31,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 32,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 32,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 33,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 33,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 34,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 34,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 34,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 35,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 35,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 36,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 36,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 37,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 37,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 38,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 38,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 38,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 39,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 39,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 39,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 40,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 40,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 41,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 41,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 41,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 42,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 42,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 43,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 43,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 44,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 44,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 44,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 45,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 45,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 46,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 46,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 47,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 47,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 48,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 48,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 48,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 49,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 49,
                            dishId = 2
                        },
                        new
                        {
                            dailyMenuId = 49,
                            dishId = 3
                        },
                        new
                        {
                            dailyMenuId = 50,
                            dishId = 1
                        },
                        new
                        {
                            dailyMenuId = 50,
                            dishId = 2
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Models.DailyMenuDto", b =>
                {
                    b.Property<int>("dailyMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dailyMenuId"));

                    b.Property<int>("category")
                        .HasColumnType("int");

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.HasKey("dailyMenuId");

                    b.ToTable("DailyMenus");

                    b.HasData(
                        new
                        {
                            dailyMenuId = 1,
                            category = 1,
                            date = new DateOnly(2025, 12, 3)
                        },
                        new
                        {
                            dailyMenuId = 2,
                            category = 2,
                            date = new DateOnly(2025, 12, 3)
                        },
                        new
                        {
                            dailyMenuId = 3,
                            category = 1,
                            date = new DateOnly(2025, 12, 4)
                        },
                        new
                        {
                            dailyMenuId = 4,
                            category = 2,
                            date = new DateOnly(2025, 12, 4)
                        },
                        new
                        {
                            dailyMenuId = 5,
                            category = 1,
                            date = new DateOnly(2025, 12, 5)
                        },
                        new
                        {
                            dailyMenuId = 6,
                            category = 2,
                            date = new DateOnly(2025, 12, 5)
                        },
                        new
                        {
                            dailyMenuId = 7,
                            category = 1,
                            date = new DateOnly(2025, 12, 6)
                        },
                        new
                        {
                            dailyMenuId = 8,
                            category = 2,
                            date = new DateOnly(2025, 12, 6)
                        },
                        new
                        {
                            dailyMenuId = 9,
                            category = 1,
                            date = new DateOnly(2025, 12, 7)
                        },
                        new
                        {
                            dailyMenuId = 10,
                            category = 2,
                            date = new DateOnly(2025, 12, 7)
                        },
                        new
                        {
                            dailyMenuId = 11,
                            category = 1,
                            date = new DateOnly(2025, 12, 8)
                        },
                        new
                        {
                            dailyMenuId = 12,
                            category = 2,
                            date = new DateOnly(2025, 12, 8)
                        },
                        new
                        {
                            dailyMenuId = 13,
                            category = 1,
                            date = new DateOnly(2025, 12, 9)
                        },
                        new
                        {
                            dailyMenuId = 14,
                            category = 2,
                            date = new DateOnly(2025, 12, 9)
                        },
                        new
                        {
                            dailyMenuId = 15,
                            category = 1,
                            date = new DateOnly(2025, 12, 10)
                        },
                        new
                        {
                            dailyMenuId = 16,
                            category = 2,
                            date = new DateOnly(2025, 12, 10)
                        },
                        new
                        {
                            dailyMenuId = 17,
                            category = 1,
                            date = new DateOnly(2025, 12, 11)
                        },
                        new
                        {
                            dailyMenuId = 18,
                            category = 2,
                            date = new DateOnly(2025, 12, 11)
                        },
                        new
                        {
                            dailyMenuId = 19,
                            category = 1,
                            date = new DateOnly(2025, 12, 12)
                        },
                        new
                        {
                            dailyMenuId = 20,
                            category = 2,
                            date = new DateOnly(2025, 12, 12)
                        },
                        new
                        {
                            dailyMenuId = 21,
                            category = 1,
                            date = new DateOnly(2025, 12, 13)
                        },
                        new
                        {
                            dailyMenuId = 22,
                            category = 2,
                            date = new DateOnly(2025, 12, 13)
                        },
                        new
                        {
                            dailyMenuId = 23,
                            category = 1,
                            date = new DateOnly(2025, 12, 14)
                        },
                        new
                        {
                            dailyMenuId = 24,
                            category = 2,
                            date = new DateOnly(2025, 12, 14)
                        },
                        new
                        {
                            dailyMenuId = 25,
                            category = 1,
                            date = new DateOnly(2025, 12, 15)
                        },
                        new
                        {
                            dailyMenuId = 26,
                            category = 2,
                            date = new DateOnly(2025, 12, 15)
                        },
                        new
                        {
                            dailyMenuId = 27,
                            category = 1,
                            date = new DateOnly(2025, 12, 16)
                        },
                        new
                        {
                            dailyMenuId = 28,
                            category = 2,
                            date = new DateOnly(2025, 12, 16)
                        },
                        new
                        {
                            dailyMenuId = 29,
                            category = 1,
                            date = new DateOnly(2025, 12, 17)
                        },
                        new
                        {
                            dailyMenuId = 30,
                            category = 2,
                            date = new DateOnly(2025, 12, 17)
                        },
                        new
                        {
                            dailyMenuId = 31,
                            category = 1,
                            date = new DateOnly(2025, 12, 18)
                        },
                        new
                        {
                            dailyMenuId = 32,
                            category = 2,
                            date = new DateOnly(2025, 12, 18)
                        },
                        new
                        {
                            dailyMenuId = 33,
                            category = 1,
                            date = new DateOnly(2025, 12, 19)
                        },
                        new
                        {
                            dailyMenuId = 34,
                            category = 2,
                            date = new DateOnly(2025, 12, 19)
                        },
                        new
                        {
                            dailyMenuId = 35,
                            category = 1,
                            date = new DateOnly(2025, 12, 20)
                        },
                        new
                        {
                            dailyMenuId = 36,
                            category = 2,
                            date = new DateOnly(2025, 12, 20)
                        },
                        new
                        {
                            dailyMenuId = 37,
                            category = 1,
                            date = new DateOnly(2025, 12, 21)
                        },
                        new
                        {
                            dailyMenuId = 38,
                            category = 2,
                            date = new DateOnly(2025, 12, 21)
                        },
                        new
                        {
                            dailyMenuId = 39,
                            category = 1,
                            date = new DateOnly(2025, 12, 22)
                        },
                        new
                        {
                            dailyMenuId = 40,
                            category = 2,
                            date = new DateOnly(2025, 12, 22)
                        },
                        new
                        {
                            dailyMenuId = 41,
                            category = 1,
                            date = new DateOnly(2025, 12, 23)
                        },
                        new
                        {
                            dailyMenuId = 42,
                            category = 2,
                            date = new DateOnly(2025, 12, 23)
                        },
                        new
                        {
                            dailyMenuId = 43,
                            category = 1,
                            date = new DateOnly(2025, 12, 24)
                        },
                        new
                        {
                            dailyMenuId = 44,
                            category = 2,
                            date = new DateOnly(2025, 12, 24)
                        },
                        new
                        {
                            dailyMenuId = 45,
                            category = 1,
                            date = new DateOnly(2025, 12, 25)
                        },
                        new
                        {
                            dailyMenuId = 46,
                            category = 2,
                            date = new DateOnly(2025, 12, 25)
                        },
                        new
                        {
                            dailyMenuId = 47,
                            category = 1,
                            date = new DateOnly(2025, 12, 26)
                        },
                        new
                        {
                            dailyMenuId = 48,
                            category = 2,
                            date = new DateOnly(2025, 12, 26)
                        },
                        new
                        {
                            dailyMenuId = 49,
                            category = 1,
                            date = new DateOnly(2025, 12, 27)
                        },
                        new
                        {
                            dailyMenuId = 50,
                            category = 2,
                            date = new DateOnly(2025, 12, 27)
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Models.DishDto", b =>
                {
                    b.Property<int>("dishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dishId"));

                    b.Property<int>("calories")
                        .HasColumnType("int");

                    b.Property<decimal>("carbohydrates")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("fat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("imgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("protein")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dishId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            dishId = 1,
                            calories = 540,
                            carbohydrates = 50m,
                            description = "Boiled chicken with white rice",
                            fat = 12m,
                            price = 3.20m,
                            protein = 35m,
                            title = "Chicken with rice"
                        },
                        new
                        {
                            dishId = 2,
                            calories = 450,
                            carbohydrates = 70m,
                            description = "Pasta with vegetables",
                            fat = 8m,
                            price = 2.80m,
                            protein = 15m,
                            title = "Vegetarian pasta"
                        },
                        new
                        {
                            dishId = 3,
                            calories = 320,
                            carbohydrates = 5m,
                            description = "Fresh grilled fish with lemon",
                            fat = 10m,
                            price = 4.50m,
                            protein = 40m,
                            title = "Grilled fish"
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Models.DishIngredientDto", b =>
                {
                    b.Property<int>("dishId")
                        .HasColumnType("int");

                    b.Property<int>("ingredientId")
                        .HasColumnType("int");

                    b.HasKey("dishId", "ingredientId");

                    b.HasIndex("ingredientId");

                    b.ToTable("DishIngredients");

                    b.HasData(
                        new
                        {
                            dishId = 1,
                            ingredientId = 1
                        },
                        new
                        {
                            dishId = 1,
                            ingredientId = 2
                        },
                        new
                        {
                            dishId = 2,
                            ingredientId = 3
                        },
                        new
                        {
                            dishId = 2,
                            ingredientId = 4
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Models.DishRatingDto", b =>
                {
                    b.Property<int>("dishRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dishRatingId"));

                    b.Property<int>("dishId")
                        .HasColumnType("int");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.HasKey("dishRatingId");

                    b.HasIndex("dishId");

                    b.ToTable("DishRatings");

                    b.HasData(
                        new
                        {
                            dishRatingId = 1,
                            dishId = 1,
                            rating = 5
                        },
                        new
                        {
                            dishRatingId = 2,
                            dishId = 2,
                            rating = 4
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Models.FavoriteDishDto", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<int>("dishId")
                        .HasColumnType("int");

                    b.HasKey("userId", "dishId");

                    b.HasIndex("dishId");

                    b.ToTable("FavoriteDishes");

                    b.HasData(
                        new
                        {
                            userId = 2,
                            dishId = 1
                        },
                        new
                        {
                            userId = 2,
                            dishId = 2
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Models.IngredientDto", b =>
                {
                    b.Property<int>("ingredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ingredientId"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ingredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            ingredientId = 1,
                            name = "Chicken breast"
                        },
                        new
                        {
                            ingredientId = 2,
                            name = "Rice"
                        },
                        new
                        {
                            ingredientId = 3,
                            name = "Pasta"
                        },
                        new
                        {
                            ingredientId = 4,
                            name = "Mixed vegetables"
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Models.NutricionGoalDto", b =>
                {
                    b.Property<int>("nutricionalGoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nutricionalGoalId"));

                    b.Property<int>("caloriesGoal")
                        .HasColumnType("int");

                    b.Property<decimal>("carbohydratesGoal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("fatsGoal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("goalSetDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("proteinsGoal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("nutricionalGoalId");

                    b.HasIndex("userId");

                    b.ToTable("NutricionGoals");

                    b.HasData(
                        new
                        {
                            nutricionalGoalId = 1,
                            caloriesGoal = 2000,
                            carbohydratesGoal = 250m,
                            fatsGoal = 70m,
                            goalSetDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            proteinsGoal = 120m,
                            userId = 2
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Models.RoleDto", b =>
                {
                    b.Property<int>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("roleId"));

                    b.Property<string>("roleTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            roleId = 1,
                            roleTitle = "Employee"
                        },
                        new
                        {
                            roleId = 2,
                            roleTitle = "Student"
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Models.UserDto", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("roleId")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.HasIndex("roleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            email = "employee@test.com",
                            firstName = "Test",
                            lastName = "Employee",
                            passwordHash = "pass123",
                            roleId = 1
                        },
                        new
                        {
                            userId = 2,
                            email = "student@test.com",
                            firstName = "Test",
                            lastName = "Student",
                            passwordHash = "pass123",
                            roleId = 2
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Models.DailyFoodIntakeDto", b =>
                {
                    b.HasOne("SmartMenza.Data.Models.DishDto", "dish")
                        .WithMany("dailyFoodIntakes")
                        .HasForeignKey("dishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenza.Data.Models.UserDto", "user")
                        .WithMany("dailyFoodIntakes")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dish");

                    b.Navigation("user");
                });

            modelBuilder.Entity("SmartMenza.Data.Models.DailyMenuDishDto", b =>
                {
                    b.HasOne("SmartMenza.Data.Models.DailyMenuDto", "dailyMenu")
                        .WithMany("dailyMenuDishes")
                        .HasForeignKey("dailyMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenza.Data.Models.DishDto", "dish")
                        .WithMany("dailyMenuDishes")
                        .HasForeignKey("dishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dailyMenu");

                    b.Navigation("dish");
                });

            modelBuilder.Entity("SmartMenza.Data.Models.DishIngredientDto", b =>
                {
                    b.HasOne("SmartMenza.Data.Models.DishDto", "dish")
                        .WithMany("dishIngredients")
                        .HasForeignKey("dishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenza.Data.Models.IngredientDto", "ingredient")
                        .WithMany("dishIngredients")
                        .HasForeignKey("ingredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dish");

                    b.Navigation("ingredient");
                });

            modelBuilder.Entity("SmartMenza.Data.Models.DishRatingDto", b =>
                {
                    b.HasOne("SmartMenza.Data.Models.DishDto", "dish")
                        .WithMany("dishRatings")
                        .HasForeignKey("dishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dish");
                });

            modelBuilder.Entity("SmartMenza.Data.Models.FavoriteDishDto", b =>
                {
                    b.HasOne("SmartMenza.Data.Models.DishDto", "dish")
                        .WithMany("favoriteDishes")
                        .HasForeignKey("dishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenza.Data.Models.UserDto", "user")
                        .WithMany("favoriteDishes")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dish");

                    b.Navigation("user");
                });

            modelBuilder.Entity("SmartMenza.Data.Models.NutricionGoalDto", b =>
                {
                    b.HasOne("SmartMenza.Data.Models.UserDto", "user")
                        .WithMany("nutricionGoals")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("SmartMenza.Data.Models.UserDto", b =>
                {
                    b.HasOne("SmartMenza.Data.Models.RoleDto", "role")
                        .WithMany("users")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("SmartMenza.Data.Models.DailyMenuDto", b =>
                {
                    b.Navigation("dailyMenuDishes");
                });

            modelBuilder.Entity("SmartMenza.Data.Models.DishDto", b =>
                {
                    b.Navigation("dailyFoodIntakes");

                    b.Navigation("dailyMenuDishes");

                    b.Navigation("dishIngredients");

                    b.Navigation("dishRatings");

                    b.Navigation("favoriteDishes");
                });

            modelBuilder.Entity("SmartMenza.Data.Models.IngredientDto", b =>
                {
                    b.Navigation("dishIngredients");
                });

            modelBuilder.Entity("SmartMenza.Data.Models.RoleDto", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("SmartMenza.Data.Models.UserDto", b =>
                {
                    b.Navigation("dailyFoodIntakes");

                    b.Navigation("favoriteDishes");

                    b.Navigation("nutricionGoals");
                });
#pragma warning restore 612, 618
        }
    }
}
