// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartMenza.Data.Data;

#nullable disable

namespace SmartMenza.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260130154046_Pokušaj")]
    partial class Pokušaj
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartMenza.Data.Entities.DailyFoodIntake", b =>
                {
                    b.Property<int>("DailyFoodIntakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DailyFoodIntakeId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DailyFoodIntakeId");

                    b.HasIndex("DishId");

                    b.HasIndex("UserId");

                    b.ToTable("DailyFoodIntakes");

                    b.HasData(
                        new
                        {
                            DailyFoodIntakeId = 1,
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = 1,
                            UserId = 2
                        },
                        new
                        {
                            DailyFoodIntakeId = 2,
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.DailyMenu", b =>
                {
                    b.Property<int>("DailyMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DailyMenuId"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("DailyMenuId");

                    b.ToTable("DailyMenus");

                    b.HasData(
                        new
                        {
                            DailyMenuId = 1,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 3)
                        },
                        new
                        {
                            DailyMenuId = 2,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 3)
                        },
                        new
                        {
                            DailyMenuId = 3,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 4)
                        },
                        new
                        {
                            DailyMenuId = 4,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 4)
                        },
                        new
                        {
                            DailyMenuId = 5,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 5)
                        },
                        new
                        {
                            DailyMenuId = 6,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 5)
                        },
                        new
                        {
                            DailyMenuId = 7,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 6)
                        },
                        new
                        {
                            DailyMenuId = 8,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 6)
                        },
                        new
                        {
                            DailyMenuId = 9,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 7)
                        },
                        new
                        {
                            DailyMenuId = 10,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 7)
                        },
                        new
                        {
                            DailyMenuId = 11,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 8)
                        },
                        new
                        {
                            DailyMenuId = 12,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 8)
                        },
                        new
                        {
                            DailyMenuId = 13,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 9)
                        },
                        new
                        {
                            DailyMenuId = 14,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 9)
                        },
                        new
                        {
                            DailyMenuId = 15,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 10)
                        },
                        new
                        {
                            DailyMenuId = 16,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 10)
                        },
                        new
                        {
                            DailyMenuId = 17,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 11)
                        },
                        new
                        {
                            DailyMenuId = 18,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 11)
                        },
                        new
                        {
                            DailyMenuId = 19,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 12)
                        },
                        new
                        {
                            DailyMenuId = 20,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 12)
                        },
                        new
                        {
                            DailyMenuId = 21,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 13)
                        },
                        new
                        {
                            DailyMenuId = 22,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 13)
                        },
                        new
                        {
                            DailyMenuId = 23,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 14)
                        },
                        new
                        {
                            DailyMenuId = 24,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 14)
                        },
                        new
                        {
                            DailyMenuId = 25,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 15)
                        },
                        new
                        {
                            DailyMenuId = 26,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 15)
                        },
                        new
                        {
                            DailyMenuId = 27,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 16)
                        },
                        new
                        {
                            DailyMenuId = 28,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 16)
                        },
                        new
                        {
                            DailyMenuId = 29,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 17)
                        },
                        new
                        {
                            DailyMenuId = 30,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 17)
                        },
                        new
                        {
                            DailyMenuId = 31,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 18)
                        },
                        new
                        {
                            DailyMenuId = 32,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 18)
                        },
                        new
                        {
                            DailyMenuId = 33,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 19)
                        },
                        new
                        {
                            DailyMenuId = 34,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 19)
                        },
                        new
                        {
                            DailyMenuId = 35,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 20)
                        },
                        new
                        {
                            DailyMenuId = 36,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 20)
                        },
                        new
                        {
                            DailyMenuId = 37,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 21)
                        },
                        new
                        {
                            DailyMenuId = 38,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 21)
                        },
                        new
                        {
                            DailyMenuId = 39,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 22)
                        },
                        new
                        {
                            DailyMenuId = 40,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 22)
                        },
                        new
                        {
                            DailyMenuId = 41,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 23)
                        },
                        new
                        {
                            DailyMenuId = 42,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 23)
                        },
                        new
                        {
                            DailyMenuId = 43,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 24)
                        },
                        new
                        {
                            DailyMenuId = 44,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 24)
                        },
                        new
                        {
                            DailyMenuId = 45,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 25)
                        },
                        new
                        {
                            DailyMenuId = 46,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 25)
                        },
                        new
                        {
                            DailyMenuId = 47,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 26)
                        },
                        new
                        {
                            DailyMenuId = 48,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 26)
                        },
                        new
                        {
                            DailyMenuId = 49,
                            Category = 1,
                            Date = new DateOnly(2025, 12, 27)
                        },
                        new
                        {
                            DailyMenuId = 50,
                            Category = 2,
                            Date = new DateOnly(2025, 12, 27)
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.DailyMenuDish", b =>
                {
                    b.Property<int>("DailyMenuId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.HasKey("DailyMenuId", "DishId");

                    b.HasIndex("DishId");

                    b.ToTable("DailyMenuDishes");

                    b.HasData(
                        new
                        {
                            DailyMenuId = 1,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 1,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 1,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 2,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 2,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 3,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 3,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 4,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 4,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 4,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 5,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 5,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 6,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 6,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 7,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 7,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 8,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 8,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 8,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 9,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 9,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 9,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 10,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 10,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 11,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 11,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 11,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 12,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 12,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 13,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 13,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 14,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 14,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 14,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 15,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 15,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 16,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 16,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 17,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 17,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 18,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 18,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 18,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 19,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 19,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 19,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 20,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 20,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 21,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 21,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 21,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 22,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 22,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 23,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 23,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 24,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 24,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 24,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 25,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 25,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 26,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 26,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 27,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 27,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 28,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 28,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 28,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 29,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 29,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 29,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 30,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 30,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 31,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 31,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 31,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 32,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 32,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 33,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 33,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 34,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 34,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 34,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 35,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 35,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 36,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 36,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 37,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 37,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 38,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 38,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 38,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 39,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 39,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 39,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 40,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 40,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 41,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 41,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 41,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 42,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 42,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 43,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 43,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 44,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 44,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 44,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 45,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 45,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 46,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 46,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 47,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 47,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 48,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 48,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 48,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 49,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 49,
                            DishId = 2
                        },
                        new
                        {
                            DailyMenuId = 49,
                            DishId = 3
                        },
                        new
                        {
                            DailyMenuId = 50,
                            DishId = 1
                        },
                        new
                        {
                            DailyMenuId = 50,
                            DishId = 2
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.Dish", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishId"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<decimal>("Carbohydrates")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Fiber")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Protein")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DishId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            Calories = 540,
                            Carbohydrates = 50m,
                            Description = "Boiled chicken with white rice",
                            Fat = 12m,
                            Fiber = 30m,
                            Price = 3.20m,
                            Protein = 35m,
                            Title = "Chicken with rice"
                        },
                        new
                        {
                            DishId = 2,
                            Calories = 450,
                            Carbohydrates = 70m,
                            Description = "Pasta with vegetables",
                            Fat = 8m,
                            Fiber = 30m,
                            Price = 2.80m,
                            Protein = 15m,
                            Title = "Vegetarian pasta"
                        },
                        new
                        {
                            DishId = 3,
                            Calories = 320,
                            Carbohydrates = 5m,
                            Description = "Fresh grilled fish with lemon",
                            Fat = 10m,
                            Fiber = 0m,
                            Price = 4.50m,
                            Protein = 40m,
                            Title = "Grilled fish"
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.DishIngredient", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("DishId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("DishIngredients");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            IngredientId = 1
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 3
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 4
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.DishRating", b =>
                {
                    b.Property<int>("DishRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishRatingId"));

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("DishRatingId");

                    b.HasIndex("DishId");

                    b.ToTable("DishRatings");

                    b.HasData(
                        new
                        {
                            DishRatingId = 1,
                            DishId = 1,
                            Rating = 5
                        },
                        new
                        {
                            DishRatingId = 2,
                            DishId = 2,
                            Rating = 4
                        },
                        new
                        {
                            DishRatingId = 3,
                            DishId = 3,
                            Rating = 3
                        },
                        new
                        {
                            DishRatingId = 4,
                            DishId = 3,
                            Rating = 4
                        },
                        new
                        {
                            DishRatingId = 5,
                            DishId = 3,
                            Rating = 4
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.FavoriteDish", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "DishId");

                    b.HasIndex("DishId");

                    b.ToTable("FavoriteDishes");

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            DishId = 1
                        },
                        new
                        {
                            UserId = 2,
                            DishId = 2
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Name = "Chicken breast"
                        },
                        new
                        {
                            IngredientId = 2,
                            Name = "Rice"
                        },
                        new
                        {
                            IngredientId = 3,
                            Name = "Pasta"
                        },
                        new
                        {
                            IngredientId = 4,
                            Name = "Mixed vegetables"
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.NutricionGoal", b =>
                {
                    b.Property<int>("NutricionalGoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NutricionalGoalId"));

                    b.Property<int>("CaloriesGoal")
                        .HasColumnType("int");

                    b.Property<decimal>("CarbohydratesGoal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FatsGoal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GoalSetDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ProteinsGoal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NutricionalGoalId");

                    b.HasIndex("UserId");

                    b.ToTable("NutricionGoals");

                    b.HasData(
                        new
                        {
                            NutricionalGoalId = 1,
                            CaloriesGoal = 2000,
                            CarbohydratesGoal = 250m,
                            FatsGoal = 70m,
                            GoalSetDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProteinsGoal = 120m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleTitle = "Employee"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleTitle = "Student"
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "employee@test.com",
                            FirstName = "Test",
                            LastName = "Employee",
                            PasswordHash = "pass123",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            Email = "student@test.com",
                            FirstName = "Test",
                            LastName = "Student",
                            PasswordHash = "pass123",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.DailyFoodIntake", b =>
                {
                    b.HasOne("SmartMenza.Data.Entities.Dish", "Dish")
                        .WithMany("DailyFoodIntakes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenza.Data.Entities.User", "User")
                        .WithMany("DailyFoodIntakes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.DailyMenuDish", b =>
                {
                    b.HasOne("SmartMenza.Data.Entities.DailyMenu", "DailyMenu")
                        .WithMany("DailyMenuDishes")
                        .HasForeignKey("DailyMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenza.Data.Entities.Dish", "Dish")
                        .WithMany("DailyMenuDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyMenu");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.DishIngredient", b =>
                {
                    b.HasOne("SmartMenza.Data.Entities.Dish", "Dish")
                        .WithMany("DishIngredients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenza.Data.Entities.Ingredient", "Ingredient")
                        .WithMany("DishIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.DishRating", b =>
                {
                    b.HasOne("SmartMenza.Data.Entities.Dish", "Dish")
                        .WithMany("DishRatings")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.FavoriteDish", b =>
                {
                    b.HasOne("SmartMenza.Data.Entities.Dish", "Dish")
                        .WithMany("FavoriteDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenza.Data.Entities.User", "User")
                        .WithMany("FavoriteDishes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.NutricionGoal", b =>
                {
                    b.HasOne("SmartMenza.Data.Entities.User", "User")
                        .WithMany("NutricionGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.User", b =>
                {
                    b.HasOne("SmartMenza.Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.DailyMenu", b =>
                {
                    b.Navigation("DailyMenuDishes");
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.Dish", b =>
                {
                    b.Navigation("DailyFoodIntakes");

                    b.Navigation("DailyMenuDishes");

                    b.Navigation("DishIngredients");

                    b.Navigation("DishRatings");

                    b.Navigation("FavoriteDishes");
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.Ingredient", b =>
                {
                    b.Navigation("DishIngredients");
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartMenza.Data.Entities.User", b =>
                {
                    b.Navigation("DailyFoodIntakes");

                    b.Navigation("FavoriteDishes");

                    b.Navigation("NutricionGoals");
                });
#pragma warning restore 612, 618
        }
    }
}
