// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartMenza.API.Data;

#nullable disable

namespace SmartMenza.API.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251031191442_AddKeysForRelacije")]
    partial class AddKeysForRelacije
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartMenza.API.Models.Cilj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPostavljanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("KalorijeCilj")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<decimal>("MastiCilj")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProteiniCilj")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UgljikohidratiCilj")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Ciljevi");
                });

            modelBuilder.Entity("SmartMenza.API.Models.DnevniMeni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<int>("JeloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JeloId");

                    b.ToTable("DnevniMeniji");
                });

            modelBuilder.Entity("SmartMenza.API.Models.DnevniUnos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumUnosa")
                        .HasColumnType("datetime2");

                    b.Property<int>("JeloId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JeloId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("DnevniUnosi");
                });

            modelBuilder.Entity("SmartMenza.API.Models.Favorit", b =>
                {
                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("JeloId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikId", "JeloId");

                    b.HasIndex("JeloId");

                    b.ToTable("Favorit");
                });

            modelBuilder.Entity("SmartMenza.API.Models.Jelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Kalorije")
                        .HasColumnType("int");

                    b.Property<decimal>("Masti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NutritivneVrijednostiId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Proteini")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SlikaPutanja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Ugljikohidrati")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Jela");
                });

            modelBuilder.Entity("SmartMenza.API.Models.JeloSastojak", b =>
                {
                    b.Property<int>("JeloId")
                        .HasColumnType("int");

                    b.Property<int>("SastojakId")
                        .HasColumnType("int");

                    b.HasKey("JeloId", "SastojakId");

                    b.HasIndex("SastojakId");

                    b.ToTable("JeloSastojci");
                });

            modelBuilder.Entity("SmartMenza.API.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UlogaId");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("SmartMenza.API.Models.OcjenaJela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JeloId")
                        .HasColumnType("int");

                    b.Property<int>("Ocjena")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JeloId");

                    b.ToTable("OcjenaJela");
                });

            modelBuilder.Entity("SmartMenza.API.Models.Sastojak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sastojci");
                });

            modelBuilder.Entity("SmartMenza.API.Models.Uloga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NazivUloge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uloge");
                });

            modelBuilder.Entity("SmartMenza.API.Models.Cilj", b =>
                {
                    b.HasOne("SmartMenza.API.Models.Korisnik", "Korisnik")
                        .WithMany("Ciljevi")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("SmartMenza.API.Models.DnevniMeni", b =>
                {
                    b.HasOne("SmartMenza.API.Models.Jelo", "Jelo")
                        .WithMany("DnevniMeniji")
                        .HasForeignKey("JeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jelo");
                });

            modelBuilder.Entity("SmartMenza.API.Models.DnevniUnos", b =>
                {
                    b.HasOne("SmartMenza.API.Models.Jelo", "Jelo")
                        .WithMany("KonzumiraniUnosi")
                        .HasForeignKey("JeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenza.API.Models.Korisnik", "Korisnik")
                        .WithMany("DnevniUnosi")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jelo");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("SmartMenza.API.Models.Favorit", b =>
                {
                    b.HasOne("SmartMenza.API.Models.Jelo", "Jelo")
                        .WithMany("FavoritanoOdKorisnika")
                        .HasForeignKey("JeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenza.API.Models.Korisnik", "Korisnik")
                        .WithMany("Favoriti")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jelo");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("SmartMenza.API.Models.JeloSastojak", b =>
                {
                    b.HasOne("SmartMenza.API.Models.Jelo", "Jelo")
                        .WithMany("JeloSastojci")
                        .HasForeignKey("JeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenza.API.Models.Sastojak", "Sastojak")
                        .WithMany("JeloSastojci")
                        .HasForeignKey("SastojakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jelo");

                    b.Navigation("Sastojak");
                });

            modelBuilder.Entity("SmartMenza.API.Models.Korisnik", b =>
                {
                    b.HasOne("SmartMenza.API.Models.Uloga", "Uloga")
                        .WithMany("Korisnici")
                        .HasForeignKey("UlogaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("SmartMenza.API.Models.OcjenaJela", b =>
                {
                    b.HasOne("SmartMenza.API.Models.Jelo", "Jelo")
                        .WithMany("Ocjene")
                        .HasForeignKey("JeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jelo");
                });

            modelBuilder.Entity("SmartMenza.API.Models.Jelo", b =>
                {
                    b.Navigation("DnevniMeniji");

                    b.Navigation("FavoritanoOdKorisnika");

                    b.Navigation("JeloSastojci");

                    b.Navigation("KonzumiraniUnosi");

                    b.Navigation("Ocjene");
                });

            modelBuilder.Entity("SmartMenza.API.Models.Korisnik", b =>
                {
                    b.Navigation("Ciljevi");

                    b.Navigation("DnevniUnosi");

                    b.Navigation("Favoriti");
                });

            modelBuilder.Entity("SmartMenza.API.Models.Sastojak", b =>
                {
                    b.Navigation("JeloSastojci");
                });

            modelBuilder.Entity("SmartMenza.API.Models.Uloga", b =>
                {
                    b.Navigation("Korisnici");
                });
#pragma warning restore 612, 618
        }
    }
}
